---
title: "Creating input files for biomarkers"
author: "Lizzie Coker"
date: "02/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(reshape2)
library(scales)
library(dplyr)
library(ggplot2)
library(superheat)
library(rowr)
set.seed(13)
```

## Data upload
```{r}

g10<-read.csv("Input/gdsc-010_matrix_results.csv")
g10$screen<-"GDSC010"
sand1<-g10

```

##Making matrices of Combo Emax
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC010_Combo_MaxE_matrix.csv")
```


##Making matrices of Bliss_matrix
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, Bliss_matrix)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$Bliss_matrix
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC010_Bliss_matrix_matrix.csv")

```


##Making matrices of Bliss_window
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, Bliss_window)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$Bliss_window
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC010_Bliss_window_matrix.csv")

```

##Making matrices of lib1_MaxE
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, lib1_MaxE)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$lib1_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC010_lib1_MaxE_matrix.csv")

```

##Making matrices of lib2_MaxE
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, lib2_MaxE)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$lib2_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC010_lib2_MaxE_matrix.csv")

```
