---
title: "Creating input files for biomarkers Sandpiper 1-GDSC009"
author: "Lizzie Coker"
date: "02/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(reshape2)
library(scales)
library(dplyr)
library(ggplot2)
library(superheat)
library(rowr)
set.seed(13)
```

## Data upload
```{r}
sand1<-read.csv("Input/sandpiper-01_matrix_results.csv")
sand1$screen<-"Sandpiper_1"
g7<-read.csv("Input/gdsc-007_matrix_results.csv")
g7$screen<-"GDSC007"
g8<-read.csv("Input/gdsc-008_matrix_results.csv")
g8$screen<-"GDSC008"
g9<-read.csv("Input/gdsc-009_matrix_results.csv")
g9$screen<-"GDSC009"

data<-rbind(sand1, g7, g8, g9)

```

##Making matrices of Combo Emax
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_Combo_MaxE_matrix.csv")


g07_combo_Emax_matrix<-g7
g07_combo_Emax_matrix$Combination<-paste(g07_combo_Emax_matrix$lib1_ID, g07_combo_Emax_matrix$lib2_ID, sep="")
g07_combo_Emax_matrix<-select(g07_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g07_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g07_combo_Emax_matrix, mean)
g07_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g07_combo_Emax_matrix$COSMIC_ID)
an <- with(g07_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g07_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_Combo_MaxE_matrix.csv")

g08_combo_Emax_matrix<-g8
g08_combo_Emax_matrix$Combination<-paste(g08_combo_Emax_matrix$lib1_ID, g08_combo_Emax_matrix$lib2_ID, sep="")
g08_combo_Emax_matrix<-select(g08_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g08_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g08_combo_Emax_matrix, mean)
g08_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g08_combo_Emax_matrix$COSMIC_ID)
an <- with(g08_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g08_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_Combo_MaxE_matrix.csv")

g09_combo_Emax_matrix<-g9
g09_combo_Emax_matrix$Combination<-paste(g09_combo_Emax_matrix$lib1_ID, g09_combo_Emax_matrix$lib2_ID, sep="")
g09_combo_Emax_matrix<-select(g09_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g09_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g09_combo_Emax_matrix, mean)
g09_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g09_combo_Emax_matrix$COSMIC_ID)
an <- with(g09_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g09_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_Combo_MaxE_matrix.csv")


#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_Combo_MaxE_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_Combo_MaxE_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_Combo_MaxE_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_Combo_MaxE_matrix.csv")
colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))

#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_combo_maxE<-cbind.fill(sand1_m,g7_m,g8_m,g9_m,  fill = NA)
#Removing repeated name row
overall_combo_maxE<-overall_combo_maxE[,-4]
overall_combo_maxE<-overall_combo_maxE[,-29]
overall_combo_maxE<-overall_combo_maxE[,-57]
colnames(overall_combo_maxE)<-gsub("X", "", colnames(overall_combo_maxE))
colnames(overall_combo_maxE)[1]<-"COSMIC_ID"
write.csv(overall_combo_maxE, "Biomarker_inputs/Sand1-GDSC009_Combo_MaxE_matrix.csv", row.names = FALSE)
```


##Making matrices of Bliss_matrix
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_Bliss_matrix_matrix<-sand1
sand1_Bliss_matrix_matrix$Combination<-paste(sand1_Bliss_matrix_matrix$lib1_ID, sand1_Bliss_matrix_matrix$lib2_ID, sep="")
sand1_Bliss_matrix_matrix<-select(sand1_Bliss_matrix_matrix, COSMIC_ID, Combination, Bliss_matrix)
sand1_Bliss_matrix_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_Bliss_matrix_matrix, mean)
sand1_Bliss_matrix_matrix$COSMIC_ID<-paste0('abc', sand1_Bliss_matrix_matrix$COSMIC_ID)
an <- with(sand1_Bliss_matrix_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_Bliss_matrix_matrix$COSMIC_ID, an)
j <- match(sand1_Bliss_matrix_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_Bliss_matrix_matrix$Bliss_matrix
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_Bliss_matrix_matrix.csv")


g07_Bliss_matrix_matrix<-g7
g07_Bliss_matrix_matrix$Combination<-paste(g07_Bliss_matrix_matrix$lib1_ID, g07_Bliss_matrix_matrix$lib2_ID, sep="")
g07_Bliss_matrix_matrix<-select(g07_Bliss_matrix_matrix, COSMIC_ID, Combination, Bliss_matrix)
g07_Bliss_matrix_matrix<-aggregate(.~COSMIC_ID + Combination, g07_Bliss_matrix_matrix, mean)
g07_Bliss_matrix_matrix$COSMIC_ID<-paste0('abc', g07_Bliss_matrix_matrix$COSMIC_ID)
an <- with(g07_Bliss_matrix_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_Bliss_matrix_matrix$COSMIC_ID, an)
j <- match(g07_Bliss_matrix_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_Bliss_matrix_matrix$Bliss_matrix
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_Bliss_matrix_matrix.csv")

g08_Bliss_matrix_matrix<-g8
g08_Bliss_matrix_matrix$Combination<-paste(g08_Bliss_matrix_matrix$lib1_ID, g08_Bliss_matrix_matrix$lib2_ID, sep="")
g08_Bliss_matrix_matrix<-select(g08_Bliss_matrix_matrix, COSMIC_ID, Combination, Bliss_matrix)
g08_Bliss_matrix_matrix<-aggregate(.~COSMIC_ID + Combination, g08_Bliss_matrix_matrix, mean)
g08_Bliss_matrix_matrix$COSMIC_ID<-paste0('abc', g08_Bliss_matrix_matrix$COSMIC_ID)
an <- with(g08_Bliss_matrix_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_Bliss_matrix_matrix$COSMIC_ID, an)
j <- match(g08_Bliss_matrix_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_Bliss_matrix_matrix$Bliss_matrix
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_Bliss_matrix_matrix.csv")

g09_Bliss_matrix_matrix<-g9
g09_Bliss_matrix_matrix$Combination<-paste(g09_Bliss_matrix_matrix$lib1_ID, g09_Bliss_matrix_matrix$lib2_ID, sep="")
g09_Bliss_matrix_matrix<-select(g09_Bliss_matrix_matrix, COSMIC_ID, Combination, Bliss_matrix)
g09_Bliss_matrix_matrix<-aggregate(.~COSMIC_ID + Combination, g09_Bliss_matrix_matrix, mean)
g09_Bliss_matrix_matrix$COSMIC_ID<-paste0('abc', g09_Bliss_matrix_matrix$COSMIC_ID)
an <- with(g09_Bliss_matrix_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_Bliss_matrix_matrix$COSMIC_ID, an)
j <- match(g09_Bliss_matrix_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_Bliss_matrix_matrix$Bliss_matrix
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_Bliss_matrix_matrix.csv")


#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_Bliss_matrix_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_Bliss_matrix_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_Bliss_matrix_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_Bliss_matrix_matrix.csv")

colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))


#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_Bliss_matrix<-cbind.fill(sand1_m,g7_m,g8_m,g9_m,  fill = NA)
#Removing repeated name row
overall_Bliss_matrix<-overall_Bliss_matrix[,-4]
overall_Bliss_matrix<-overall_Bliss_matrix[,-29]
overall_Bliss_matrix<-overall_Bliss_matrix[,-57]

colnames(overall_Bliss_matrix)<-gsub("X", "", colnames(overall_Bliss_matrix))
colnames(overall_Bliss_matrix)[1]<-"COSMIC_ID"
write.csv(overall_Bliss_matrix, "Biomarker_inputs/Sand1-GDSC009_Bliss_matrix_matrix.csv", row.names = FALSE)
```


##Making matrices of Bliss_window
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_Bliss_window_matrix<-sand1
sand1_Bliss_window_matrix$Combination<-paste(sand1_Bliss_window_matrix$lib1_ID, sand1_Bliss_window_matrix$lib2_ID, sep="")
sand1_Bliss_window_matrix<-select(sand1_Bliss_window_matrix, COSMIC_ID, Combination, Bliss_window)
sand1_Bliss_window_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_Bliss_window_matrix, mean)
sand1_Bliss_window_matrix$COSMIC_ID<-paste0('abc', sand1_Bliss_window_matrix$COSMIC_ID)
an <- with(sand1_Bliss_window_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_Bliss_window_matrix$COSMIC_ID, an)
j <- match(sand1_Bliss_window_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_Bliss_window_matrix$Bliss_window
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_Bliss_window_matrix.csv")


g07_Bliss_window_matrix<-g7
g07_Bliss_window_matrix$Combination<-paste(g07_Bliss_window_matrix$lib1_ID, g07_Bliss_window_matrix$lib2_ID, sep="")
g07_Bliss_window_matrix<-select(g07_Bliss_window_matrix, COSMIC_ID, Combination, Bliss_window)
g07_Bliss_window_matrix<-aggregate(.~COSMIC_ID + Combination, g07_Bliss_window_matrix, mean)
g07_Bliss_window_matrix$COSMIC_ID<-paste0('abc', g07_Bliss_window_matrix$COSMIC_ID)
an <- with(g07_Bliss_window_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_Bliss_window_matrix$COSMIC_ID, an)
j <- match(g07_Bliss_window_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_Bliss_window_matrix$Bliss_window
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_Bliss_window_matrix.csv")

g08_Bliss_window_matrix<-g8
g08_Bliss_window_matrix$Combination<-paste(g08_Bliss_window_matrix$lib1_ID, g08_Bliss_window_matrix$lib2_ID, sep="")
g08_Bliss_window_matrix<-select(g08_Bliss_window_matrix, COSMIC_ID, Combination, Bliss_window)
g08_Bliss_window_matrix<-aggregate(.~COSMIC_ID + Combination, g08_Bliss_window_matrix, mean)
g08_Bliss_window_matrix$COSMIC_ID<-paste0('abc', g08_Bliss_window_matrix$COSMIC_ID)
an <- with(g08_Bliss_window_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_Bliss_window_matrix$COSMIC_ID, an)
j <- match(g08_Bliss_window_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_Bliss_window_matrix$Bliss_window
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_Bliss_window_matrix.csv")

g09_Bliss_window_matrix<-g9
g09_Bliss_window_matrix$Combination<-paste(g09_Bliss_window_matrix$lib1_ID, g09_Bliss_window_matrix$lib2_ID, sep="")
g09_Bliss_window_matrix<-select(g09_Bliss_window_matrix, COSMIC_ID, Combination, Bliss_window)
g09_Bliss_window_matrix<-aggregate(.~COSMIC_ID + Combination, g09_Bliss_window_matrix, mean)
g09_Bliss_window_matrix$COSMIC_ID<-paste0('abc', g09_Bliss_window_matrix$COSMIC_ID)
an <- with(g09_Bliss_window_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_Bliss_window_matrix$COSMIC_ID, an)
j <- match(g09_Bliss_window_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_Bliss_window_matrix$Bliss_window
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_Bliss_window_matrix.csv")



#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_Bliss_window_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_Bliss_window_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_Bliss_window_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_Bliss_window_matrix.csv")
colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))

#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_Bliss_window<-cbind.fill(sand1_m,g7_m,g8_m,g9_m, fill = NA)
#Removing repeated name row
overall_Bliss_window<-overall_Bliss_window[,-4]
overall_Bliss_window<-overall_Bliss_window[,-29]
overall_Bliss_window<-overall_Bliss_window[,-57]
colnames(overall_Bliss_window)<-gsub("X", "", colnames(overall_Bliss_window))
colnames(overall_Bliss_window)[1]<-"COSMIC_ID"
write.csv(overall_Bliss_window, "Biomarker_inputs/Sand1-GDSC009_Bliss_window_matrix.csv", row.names = FALSE)
```

##Making matrices of lib1_MaxE
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_lib1_MaxE_matrix<-sand1
sand1_lib1_MaxE_matrix$Combination<-paste(sand1_lib1_MaxE_matrix$lib1_ID, sand1_lib1_MaxE_matrix$lib2_ID, sep="")
sand1_lib1_MaxE_matrix<-select(sand1_lib1_MaxE_matrix, COSMIC_ID, Combination, lib1_MaxE)
sand1_lib1_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_lib1_MaxE_matrix, mean)
sand1_lib1_MaxE_matrix$COSMIC_ID<-paste0('abc', sand1_lib1_MaxE_matrix$COSMIC_ID)
an <- with(sand1_lib1_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_lib1_MaxE_matrix$COSMIC_ID, an)
j <- match(sand1_lib1_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_lib1_MaxE_matrix$lib1_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_lib1_MaxE_matrix.csv")


g07_lib1_MaxE_matrix<-g7
g07_lib1_MaxE_matrix$Combination<-paste(g07_lib1_MaxE_matrix$lib1_ID, g07_lib1_MaxE_matrix$lib2_ID, sep="")
g07_lib1_MaxE_matrix<-select(g07_lib1_MaxE_matrix, COSMIC_ID, Combination, lib1_MaxE)
g07_lib1_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g07_lib1_MaxE_matrix, mean)
g07_lib1_MaxE_matrix$COSMIC_ID<-paste0('abc', g07_lib1_MaxE_matrix$COSMIC_ID)
an <- with(g07_lib1_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_lib1_MaxE_matrix$COSMIC_ID, an)
j <- match(g07_lib1_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_lib1_MaxE_matrix$lib1_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_lib1_MaxE_matrix.csv")

g08_lib1_MaxE_matrix<-g8
g08_lib1_MaxE_matrix$Combination<-paste(g08_lib1_MaxE_matrix$lib1_ID, g08_lib1_MaxE_matrix$lib2_ID, sep="")
g08_lib1_MaxE_matrix<-select(g08_lib1_MaxE_matrix, COSMIC_ID, Combination, lib1_MaxE)
g08_lib1_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g08_lib1_MaxE_matrix, mean)
g08_lib1_MaxE_matrix$COSMIC_ID<-paste0('abc', g08_lib1_MaxE_matrix$COSMIC_ID)
an <- with(g08_lib1_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_lib1_MaxE_matrix$COSMIC_ID, an)
j <- match(g08_lib1_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_lib1_MaxE_matrix$lib1_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_lib1_MaxE_matrix.csv")

g09_lib1_MaxE_matrix<-g9
g09_lib1_MaxE_matrix$Combination<-paste(g09_lib1_MaxE_matrix$lib1_ID, g09_lib1_MaxE_matrix$lib2_ID, sep="")
g09_lib1_MaxE_matrix<-select(g09_lib1_MaxE_matrix, COSMIC_ID, Combination, lib1_MaxE)
g09_lib1_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g09_lib1_MaxE_matrix, mean)
g09_lib1_MaxE_matrix$COSMIC_ID<-paste0('abc', g09_lib1_MaxE_matrix$COSMIC_ID)
an <- with(g09_lib1_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_lib1_MaxE_matrix$COSMIC_ID, an)
j <- match(g09_lib1_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_lib1_MaxE_matrix$lib1_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_lib1_MaxE_matrix.csv")

#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_lib1_MaxE_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_lib1_MaxE_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_lib1_MaxE_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_lib1_MaxE_matrix.csv")
colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))

#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_lib1_MaxE<-cbind.fill(sand1_m,g7_m,g8_m,g9_m, fill = NA)
#Removing repeated name row
overall_lib1_MaxE<-overall_lib1_MaxE[,-4]
overall_lib1_MaxE<-overall_lib1_MaxE[,-29]
overall_lib1_MaxE<-overall_lib1_MaxE[,-57]
colnames(overall_lib1_MaxE)<-gsub("X", "", colnames(overall_lib1_MaxE))
colnames(overall_lib1_MaxE)[1]<-"COSMIC_ID"
write.csv(overall_lib1_MaxE, "Biomarker_inputs/Sand1-GDSC009_lib1_MaxE_matrix.csv", row.names = FALSE)
```

##Making matrices of lib2_MaxE
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_lib2_MaxE_matrix<-sand1
sand1_lib2_MaxE_matrix$Combination<-paste(sand1_lib2_MaxE_matrix$lib1_ID, sand1_lib2_MaxE_matrix$lib2_ID, sep="")
sand1_lib2_MaxE_matrix<-select(sand1_lib2_MaxE_matrix, COSMIC_ID, Combination, lib2_MaxE)
sand1_lib2_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_lib2_MaxE_matrix, mean)
sand1_lib2_MaxE_matrix$COSMIC_ID<-paste0('abc', sand1_lib2_MaxE_matrix$COSMIC_ID)
an <- with(sand1_lib2_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_lib2_MaxE_matrix$COSMIC_ID, an)
j <- match(sand1_lib2_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_lib2_MaxE_matrix$lib2_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_lib2_MaxE_matrix.csv")


g07_lib2_MaxE_matrix<-g7
g07_lib2_MaxE_matrix$Combination<-paste(g07_lib2_MaxE_matrix$lib1_ID, g07_lib2_MaxE_matrix$lib2_ID, sep="")
g07_lib2_MaxE_matrix<-select(g07_lib2_MaxE_matrix, COSMIC_ID, Combination, lib2_MaxE)
g07_lib2_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g07_lib2_MaxE_matrix, mean)
g07_lib2_MaxE_matrix$COSMIC_ID<-paste0('abc', g07_lib2_MaxE_matrix$COSMIC_ID)
an <- with(g07_lib2_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_lib2_MaxE_matrix$COSMIC_ID, an)
j <- match(g07_lib2_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_lib2_MaxE_matrix$lib2_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_lib2_MaxE_matrix.csv")

g08_lib2_MaxE_matrix<-g8
g08_lib2_MaxE_matrix$Combination<-paste(g08_lib2_MaxE_matrix$lib1_ID, g08_lib2_MaxE_matrix$lib2_ID, sep="")
g08_lib2_MaxE_matrix<-select(g08_lib2_MaxE_matrix, COSMIC_ID, Combination, lib2_MaxE)
g08_lib2_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g08_lib2_MaxE_matrix, mean)
g08_lib2_MaxE_matrix$COSMIC_ID<-paste0('abc', g08_lib2_MaxE_matrix$COSMIC_ID)
an <- with(g08_lib2_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_lib2_MaxE_matrix$COSMIC_ID, an)
j <- match(g08_lib2_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_lib2_MaxE_matrix$lib2_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_lib2_MaxE_matrix.csv")

g09_lib2_MaxE_matrix<-g9
g09_lib2_MaxE_matrix$Combination<-paste(g09_lib2_MaxE_matrix$lib1_ID, g09_lib2_MaxE_matrix$lib2_ID, sep="")
g09_lib2_MaxE_matrix<-select(g09_lib2_MaxE_matrix, COSMIC_ID, Combination, lib2_MaxE)
g09_lib2_MaxE_matrix<-aggregate(.~COSMIC_ID + Combination, g09_lib2_MaxE_matrix, mean)
g09_lib2_MaxE_matrix$COSMIC_ID<-paste0('abc', g09_lib2_MaxE_matrix$COSMIC_ID)
an <- with(g09_lib2_MaxE_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_lib2_MaxE_matrix$COSMIC_ID, an)
j <- match(g09_lib2_MaxE_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_lib2_MaxE_matrix$lib2_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_lib2_MaxE_matrix.csv")

#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_lib2_MaxE_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_lib2_MaxE_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_lib2_MaxE_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_lib2_MaxE_matrix.csv")
colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))

#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_lib2_MaxE<-cbind.fill(sand1_m,g7_m,g8_m,g9_m,  fill = NA)
#Removing repeated name row
overall_lib2_MaxE<-overall_lib2_MaxE[,-4]
overall_lib2_MaxE<-overall_lib2_MaxE[,-29]
overall_lib2_MaxE<-overall_lib2_MaxE[,-57]
colnames(overall_lib2_MaxE)<-gsub("X", "", colnames(overall_lib2_MaxE))
colnames(overall_lib2_MaxE)[1]<-"COSMIC_ID"
write.csv(overall_lib2_MaxE, "Biomarker_inputs/Sand1-GDSC009_lib2_MaxE_matrix.csv", row.names = FALSE)
```

##Making matrices of combo_Emax
```{r}
#For each metric used for biomarker input, need to create matrices of these inputs for GDSCTools ANOVAs
sand1_combo_Emax_matrix<-sand1
sand1_combo_Emax_matrix$Combination<-paste(sand1_combo_Emax_matrix$lib1_ID, sand1_combo_Emax_matrix$lib2_ID, sep="")
sand1_combo_Emax_matrix<-select(sand1_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
sand1_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, sand1_combo_Emax_matrix, mean)
sand1_combo_Emax_matrix$COSMIC_ID<-paste0('abc', sand1_combo_Emax_matrix$COSMIC_ID)
an <- with(sand1_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(sand1_combo_Emax_matrix$COSMIC_ID, an)
j <- match(sand1_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- sand1_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/Sandpiper1_combo_Emax_matrix.csv")


g07_combo_Emax_matrix<-g7
g07_combo_Emax_matrix$Combination<-paste(g07_combo_Emax_matrix$lib1_ID, g07_combo_Emax_matrix$lib2_ID, sep="")
g07_combo_Emax_matrix<-select(g07_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g07_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g07_combo_Emax_matrix, mean)
g07_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g07_combo_Emax_matrix$COSMIC_ID)
an <- with(g07_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g07_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g07_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g07_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC007_combo_Emax_matrix.csv")

g08_combo_Emax_matrix<-g8
g08_combo_Emax_matrix$Combination<-paste(g08_combo_Emax_matrix$lib1_ID, g08_combo_Emax_matrix$lib2_ID, sep="")
g08_combo_Emax_matrix<-select(g08_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g08_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g08_combo_Emax_matrix, mean)
g08_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g08_combo_Emax_matrix$COSMIC_ID)
an <- with(g08_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g08_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g08_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g08_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC008_combo_Emax_matrix.csv")

g09_combo_Emax_matrix<-g9
g09_combo_Emax_matrix$Combination<-paste(g09_combo_Emax_matrix$lib1_ID, g09_combo_Emax_matrix$lib2_ID, sep="")
g09_combo_Emax_matrix<-select(g09_combo_Emax_matrix, COSMIC_ID, Combination, combo_MaxE)
g09_combo_Emax_matrix<-aggregate(.~COSMIC_ID + Combination, g09_combo_Emax_matrix, mean)
g09_combo_Emax_matrix$COSMIC_ID<-paste0('abc', g09_combo_Emax_matrix$COSMIC_ID)
an <- with(g09_combo_Emax_matrix, sort(unique(c(as.character(COSMIC_ID), as.character(Combination)))))
M <- array(0, c(length(an), length(an)), list(an, an))
i <- match(g09_combo_Emax_matrix$COSMIC_ID, an)
j <- match(g09_combo_Emax_matrix$Combination, an)
M[cbind(i,j)] <- M[cbind(j,i)] <- g09_combo_Emax_matrix$combo_MaxE
newM<-M[, -grep("abc", colnames(M))]
thirdM<-newM[grep("abc", row.names(newM)),]
row.names(thirdM)<-sub("abc", "", row.names(thirdM))
write.csv(thirdM, "Biomarker_inputs/GDSC009_combo_Emax_matrix.csv")

#Merging all matrices together
sand1_m<-read.csv("Biomarker_inputs/Sandpiper1_combo_Emax_matrix.csv")
g7_m<-read.csv("Biomarker_inputs/GDSC007_combo_Emax_matrix.csv")
g8_m<-read.csv("Biomarker_inputs/GDSC008_combo_Emax_matrix.csv")
g9_m<-read.csv("Biomarker_inputs/GDSC009_combo_Emax_matrix.csv")
colnames(sand1_m)<-gsub("X", "", colnames(sand1_m))
colnames(g7_m)<-gsub("X", "", colnames(g7_m))
colnames(g8_m)<-gsub("X", "", colnames(g8_m))
colnames(g9_m)<-gsub("X", "", colnames(g9_m))

#adding differential labelling to distinguish between 007 and 008 screen for repeated combination
colnames(g7_m)<-gsub("24312574", "2431257407", colnames(g7_m))
colnames(g8_m)<-gsub("24312574", "2431257408", colnames(g8_m))

overall_combo_Emax<-cbind.fill(sand1_m,g7_m,g8_m,g9_m,  fill = NA)
#Removing repeated name row
overall_combo_Emax<-overall_combo_Emax[,-4]
overall_combo_Emax<-overall_combo_Emax[,-29]
overall_combo_Emax<-overall_combo_Emax[,-57]
colnames(overall_combo_Emax)<-gsub("X", "", colnames(overall_combo_Emax))
colnames(overall_combo_Emax)[1]<-"COSMIC_ID"
write.csv(overall_combo_Emax, "Biomarker_inputs/Sand1-GDSC009_combo_Emax_matrix.csv", row.names = FALSE)
```
