---
title: "Supp Figure 2A/B"
author: "Lizzie Coker"
date: "18/06/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(reshape2)
library(scales)
library(dplyr)
library(ggplot2)
library(superheat)
library(rowr)
library(ggplot2)
library(dplyr)
library(magrittr)
library(knitr)
library(lubridate)
library(tidyr)
library(RColorBrewer)
library(reshape2)
library(knitr)
library(kableExtra)
library(scales)
library(ggpubr)
library(stats)
library(ggridges)
library(hexbin)
set.seed(13)
```

## Data upload
```{r}
sand1<-read.csv("Input/sandpiper-01_matrix_results.csv")
sand1$screen<-"Sandpiper_1"
g7<-read.csv("Input/gdsc-007_matrix_results.csv")
g7$screen<-"GDSC007"
g8<-read.csv("Input/gdsc-008_matrix_results.csv")
g8$screen<-"GDSC008"
g9<-read.csv("Input/gdsc-009_matrix_results.csv")
g9$screen<-"GDSC009"
g10<-read.csv("Input/gdsc-010_matrix_results.csv")
g10$screen<-"GDSC010"

data<-rbind(sand1, g7, g8, g9, g10)
```



```{r}
data_S1E_1<-data
data_S1E_2<-data
#Rename lib1 and lib2 ln IC50s as single agent ln IC50s
names(data_S1E_1)[17]<-"Sandpiper_ln_IC50"
names(data_S1E_2)[28]<-"Sandpiper_ln_IC50"
#Create compound variable of cell line ID and drug ID for matching to monotherapy data
data_S1E_1$test<-paste(data_S1E_1$SIDM, data_S1E_1$lib1_ID, sep="_")
data_S1E_2$test<-paste(data_S1E_2$SIDM, data_S1E_2$lib2_ID, sep="_")
data_S1E_1<-select(data_S1E_1, test, Sandpiper_ln_IC50)
data_S1E_2<-select(data_S1E_2, test, Sandpiper_ln_IC50)
data_S1E<-rbind(data_S1E_1, data_S1E_2)
#Aggregate replicates by mean
data_S1E<-aggregate(x = data_S1E$Sandpiper_ln_IC50,
                by = list(data_S1E$test),              
                FUN = mean)   
names(data_S1E)[2]<-"Sandpiper_ln_IC50"
names(data_S1E)[1]<-"test"
```

##Comparison with GDSC 2 monotherapies - identical protocol, correlation of 85.46%
```{r}
#Read in previously published single agent ln_IC50s
gdsc2<-read.csv("Input/GDSC2_fitted_dose_response_25Feb20.csv")
gdsc2<-select(gdsc2, SANGER_MODEL_ID, DRUG_ID, LN_IC50)
names(gdsc2)[3]<-"GDSC2_ln_IC50"
#Create compound variable of cell line ID and drug ID for matching to combination single agent ln IC50s
gdsc2$test<-paste(gdsc2$SANGER_MODEL_ID, gdsc2$DRUG_ID, sep="_")
gdsc2<-gdsc2[,-1:-2]
#Aggregate replicates by mean
gdsc2<-aggregate(x = gdsc2$GDSC2_ln_IC50,
                 by = list(gdsc2$test),              
                 FUN = mean)   
names(gdsc2)[2]<-"GDSC2_ln_IC50"
names(gdsc2)[1]<-"test"

all_S1E<-merge(data_S1E, gdsc2, by="test")

#correlation between combination study ln IC50s and previously-published ln IC50s
cor(all_S1E$Sandpiper_ln_IC50, all_S1E$GDSC2_ln_IC50)

plot(all_S1E$GDSC2_ln_IC50, all_S1E$Sandpiper_ln_IC50, xlab="ln(IC50) in GDSC2", ylab="ln(IC50) for single agents in this study", pch=20)

#735 cell lines in common, 6 drugs
```


##Comparison with GDSC 1 monotherapies - similar protocol, correlation of 74.30%
```{r}
#Read in previously published single agent ln_IC50s
gdsc1<-read.csv("Input/GDSC1_fitted_dose_response_24Jul22.csv")
gdsc1<-select(gdsc1, SANGER_MODEL_ID, DRUG_ID, LN_IC50)
names(gdsc1)[3]<-"GDSC1_ln_IC50"
#Create compound variable of cell line ID and drug ID for matching to combination single agent ln IC50s
gdsc1$test<-paste(gdsc1$SANGER_MODEL_ID, gdsc1$DRUG_ID, sep="_")
gdsc1<-gdsc1[,-1:-2]
#Aggregate replicates by mean
gdsc1<-aggregate(x = gdsc1$GDSC1_ln_IC50,
                 by = list(gdsc1$test),              
                 FUN = mean)   
names(gdsc1)[2]<-"GDSC1_ln_IC50"
names(gdsc1)[1]<-"test"

all_S1E<-merge(data_S1E, gdsc1, by="test")

#correlation between combination study ln IC50s and previously-published ln IC50s
cor(all_S1E$Sandpiper_ln_IC50, all_S1E$GDSC1_ln_IC50)

plot(all_S1E$GDSC1_ln_IC50, all_S1E$Sandpiper_ln_IC50, xlab="ln(IC50) in GDSC1", ylab="ln(IC50) for single agents in this study", pch=20)

#699 cell lines in common, two compounds in common
```
###PRISM

There are 13 drugs and 346 cell lines in common between the two screens. There is a correlation of 51.3%, where data is available. 
```{r}
prism<-read.csv("Input/PRISM/Drug_sensitivity_(PRISM_Repurposing_Primary_Screen).csv")
row.names(prism)<-prism[,1]
common_drugs<-read.csv("PRISM_Sanger_mapping.csv")

NameList <- unique(common_drugs$PRISM_name)
idx <- match(NameList, names(prism))
NewDF <- prism[,idx] 
NewDF$BROAD_ID<-row.names(NewDF)
test<-melt(NewDF)
names(test)[2]<-"PRISM_name"
names(test)[3]<-"PRISM_ln_IC50"

test<-merge(test, common_drugs, by= "PRISM_name")
test<-test[,-1]
cmp<-read.csv("Input/PRISM/model_list_20230608.csv")
cmp<-select(cmp, "model_id", "BROAD_ID")
test<-merge(test, cmp, by= "BROAD_ID")
test<-test[,-1]
test$test<-paste(test$model_id, test$Sanger.ID, sep="_")
test<-test[,-2:-4]

prism_results<-aggregate(x = test$PRISM_ln_IC50,
                 by = list(test$test),              
                 FUN = mean)   
names(prism_results)[2]<-"PRISM_ln_IC50"
names(prism_results)[1]<-"test"


all_prism<-merge(data_S1E, prism_results, by="test")
all_prism<-all_prism[complete.cases(all_prism), ]

#correlation between combination study ln IC50s and previously-published ln IC50s
cor(all_prism$Sandpiper_ln_IC50, all_prism$PRISM_ln_IC50)

plot(all_prism$PRISM_ln_IC50, all_prism$Sandpiper_ln_IC50, xlab="ln(IC50) in PRISM", ylab="ln(IC50) for single agents in this study", pch=20)

#write.csv(all_prism, "A.csv")

```

